modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All rights reserved"
issueTrackerURL="https://github.com/Than00ber/ProductivityEnchantments/issues" #optional

[[mods]] #mandatory
modId="productivityenchantments" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Productivity Enchantments Mod" #mandatory
#displayURL="http://example.com/" #optional
logoFile="productivityenchantments.png" #optional
credits="Forge maintainer, Sushiz" #optional
authors="Than00ber" #optional
description='''
    As the title suggests, this mod adds 8 vanilla-like enchantments aiming at increasing your productivity by helping you complete tedious tasks like farming, mining and even terraforming while being as balanced as possible to fit the game's theme.
'''

[[dependencies.productivityenchantments]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[35,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.productivityenchantments]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
